### ISSUE TITLE
Not Found error

### ISSUE THREAD

**Issue by feerrenrut** [meiji163/gh-notify#11]
Environments (Windows 10) tested:
- git-bash for Windows, without fuzzy find installed.
- Command prompt (cmd.exe / conhost)
- Powershell

In all cases, the following errors are given, `$` used to indicated prompt.
```
$ gh notify
error: install `fzf` or use the -s flag
$ gh notify -s
.gh: Not Found (HTTP 404)
$ gh notify -ps
.gh: Not Found (HTTP 404)
```

**Comment by LangLangBart** [comment]
I found a similar sounding problem.
- https://github.com/kawarimidoll/gh-graph/issues/1 (25/Aug/21)

Could you try running the following lines of code one after the other? I assume it is only a compatibility problem for Windows and hopefully the second line will work.
```zsh
gh api -X GET /notifications -f all=true
gh api -X GET notifications -f all=true
```

The change came with 2529d52ad05be4cfe3cbb6d9069e8f9887d0a109.

**Comment by feerrenrut** [comment]
As you expected @LangLangBart:

```sh
$ gh api -X GET /notifications -f all=true
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}
gh: Not Found (HTTP 404)
```
```sh
$ gh api -X GET notifications -f all=true
[
  {
    "id": ....
```
