### ISSUE TITLE
Preview does not match when notification is for a pre-release

### ISSUE THREAD

**Issue by rEnr3n** [meiji163/gh-notify#23]
When there is a notification for a `pre-release`, the preview shows the latest `release` instead of the `pre-release`. See screenshot below:

![2022-10-29_10:36:51+0800](https://user-images.githubusercontent.com/18730618/198785691-214493c8-0478-4719-8e69-71ff3ea02a1f.png)

`Ctrl+b` opens this [link](https://github.com/home-assistant/core/releases/tag/2022.10.5). It should be this [one](https://github.com/home-assistant/core/releases/tag/2022.11.0b2).

**Comment by LangLangBart** [comment]
## Issue
The original problem is that calling the[ REST API for notifications](https://docs.github.com/en/rest/activity/notifications#list-repository-notifications-for-the-authenticated-user) does not return the `tagName` of the release.

```json
  {
    "id": "4675083817",
    "unread": false,
    "reason": "subscribed",
    "updated_at": "2022-10-24T20:10:47Z",
    "last_read_at": "2022-10-24T20:24:57Z",
    "subject": {
      "title": "boonGUI v2.6.5",
      "url": "https://api.github.com/repos/LangLangBart/boonGUI/releases/80834449",
      "latest_comment_url": "https://api.github.com/repos/LangLangBart/boonGUI/releases/80834449",
      "type": "Release"
    },
    "repository": {
...
```

The script later calls:
```zsh
gh release view -R home-assistant/core
```

But this does not consider `pre-releases`.

`gh` is able to also show `pre-releases`, but only when it gets the tag number.

```zsh
gh release view -R home-assistant/core 2022.11.0b2
```

To mitigate the problem, an additional `GraphQL API` query could be performed to get the latest release tag.

---
## GraphQL
### Query to get latest release tag
```graphql
query ($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    releases(last: 1, orderBy: {direction: ASC, field: CREATED_AT}) {
      nodes {
        tagName
        isPrerelease
      }
    }
  }
}
```

### Result  for home-assistant/core
```json
{
  "data": {
    "repository": {
      "releases": {
        "nodes": [
          {
            "tagName": "2022.11.0b2",
            "isPrerelease": true
          }
        ]
      }
    }
  }
}
```

```zsh
TAG=$(gh api graphql --raw-field owner=home-assistant --raw-field name=core --raw-field query=$QUERY --jq '.data.repository.releases.nodes | .[].tagName')
gh release view -R home-assistant/core $TAG
# 2022.11.0b2
# Pre-release • balloob released this about 1 hour ago
...
```

---

## final thoughts
- the issue can be mitigated as seen above, for a better solution we need GitHub to provide a `GraphQL API` for notifications. The goal would be to retrieve hundreds of notification details with a single request.

According to the official [GitHub public roadmap](https://github.com/orgs/github/projects/4247/views/1), this does not seem to be planned.

- Related threads
  - [Get notification list via GraphQL API](https://web.archive.org/web/20220220041854/https://github.community/t/get-notification-list-via-graphql-api/13836) - 13/Mar/19
  - [Can't get release neither comment using their id via GraphQL API](https://github.com/community/community/discussions/24833) - 7/Oct/19
  - [Notifications GraphQL API](https://github.com/community/community/discussions/13056) - 19/Mar/22
