### ISSUE TITLE
REST API version system

### ISSUE THREAD

**Issue by LangLangBart** [meiji163/gh-notify#33]
### Information:
- GitHub published their [REST API with API versioning](https://github.blog/2022-11-28-to-infinity-and-beyond-enabling-the-future-of-githubs-rest-api-with-api-versioning/).

Starting with `28/Nov/22` you must specify which `REST API` version to use whenever you make a request.
    
```zsh
curl --header "X-GitHub-Api-Version:2022-11-28" https://api.github.com/zen
```
    
Requests without the `X-GitHub-Api-Version` header will default to use the `2022-11-28` version (for now).

#### related threads:
- Bog Post: [To infinity and beyond: enabling the future of GitHub’s REST API with API versioning](https://github.blog/2022-11-28-to-infinity-and-beyond-enabling-the-future-of-githubs-rest-api-with-api-versioning/) (28/Nov/22)
- HackerNews discussion: [Enabling the Future of GitHub's REST API with API Versioning (github.blog)](https://news.ycombinator.com/item?id=33779549) (28/Nov/22)
- GitHub Docs: [GitHub Docs - REST API - API Versions](https://docs.github.com/en/rest/overview/api-versions)

**Comment by meiji163** [comment]
Nice! Didn't know about this
