### ISSUE TITLE
Show "open" notifications

### ISSUE THREAD

**Issue by ajdubovoy** [meiji163/gh-notify#47]
I'm so appreciative this exists!

As with probably other Github users, I don't really organize my notifications by whether they're unread or not. If I'm done with a notification, I mark it as "done".

As far as I can there's no way in this extension to search for "is:open" notifications. It would be awesome to have:

1. A way to show "is:open"
2. A way to show "is:done"
3. A way to mark a notification as open/done

Thanks so much

**Comment by LangLangBart** [comment]
> _A way to show "is:open"_
- This could be done by implementing a filter that checks if the notification is a PR/issue and then checks if it is still open.
- The downside
  - notifications retrieved from Github do not contain the information about the status of a PR/issue, you would have to make an additional call for each notification, which would cost time
  - I would love to have color coded notifications
    - green: open
    - red: closed
    - purple: merged
  - Image example from another extension

<img src="https://github.com/meiji163/gh-notify/assets/92653266/8a379eac-5e3e-4a13-b94b-2ac355c7729b" width="600">


- Related threads
  - [Get notification list via GraphQL API](https://web.archive.org/web/20220220041854/https://github.community/t/get-notification-list-via-graphql-api/13836) - 13/Mar/19
  - [Can't get release neither comment using their id via GraphQL API](https://github.com/community/community/discussions/24833) - 7/Oct/19
  - [Notifications GraphQL API](https://github.com/community/community/discussions/13056) - 19/Mar/22



> _A way to show "is:done"_
> _A way to mark a notification as open/done_
- GitHub does not provide this functionality through its API
- Related thread
  - [Expose notification mark as done functionality through API #15669](https://github.com/orgs/community/discussions/15669)

---
## Conclusion
- Implementing your ideas depends more on GitHub's API.
  - Filtering notifications for issues/PR and checking if they are still open is worth a try, leaving the ticket open for now.
  - it could be added as an additional flag, allowing the user to decide if they prefer speed or more details

**Comment by ajdubovoy** [comment]
Thanks so much for the considered response! With the is:open filtering I meant that the notification has not been marked done (not that the associated issue or pr is still open, if applicable).

It's wild that they don't provide access to this in the api but do to lots of other details about notifications.

Anyway, the color coding is still a lovely idea and I so appreciate your work on this

**Comment by LangLangBart** [comment]
When interacting with the GitHub WebUI, one can see the `API` calls being made from the `Inspect` page on the  `Querio` tab (ref: [querio.app](https://querio.app/)). The call to mark notifications as `Done` is possible, but it does require an additional `authenticity_token`. 

<img src="https://github.com/meiji163/gh-notify/assets/92653266/10e5c03a-e1a8-4a3d-bac2-889d7e2dc22e" width="800">

<img src="https://github.com/meiji163/gh-notify/assets/92653266/3a9b503a-ab88-4bdd-9672-968bbeec76f7" width="800">

---

I'm closing the ticket for now, as GitHub does not readily allow the required `API` calls and no one knows when these undocumented `API` calls will be made available to the public without using an `authenticity_token`. Also, generating these `authenticity_token` doesn't seem to be possible, I couldn't find a way to generate them.

---

as for the other idea:

> _Filtering notifications for issues/PR and checking if they are still open is worth a try, leaving the ticket open for now._

I tested it, but I quickly got rate limitations when I made many calls with in short succession to check the state of each issue/pr. A `GraphQL` API for GitHub notifications would be great.

**Comment by rmacklin** [comment]
Re:
> > _A way to mark a notification as open/done_
> 
> * GitHub does not provide this functionality through its API

Is that not what this is:
https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#mark-a-thread-as-done
?

**Comment by LangLangBart** [comment]
> Re:
> 
> > > _A way to mark a notification as open/done_
> > 
> > 
> > 
> > * GitHub does not provide this functionality through its API
> 
> Is that not what this is: https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#mark-a-thread-as-done ?


This appears to be a recent addition to the `REST API`. According to the `Wayback` machine, the
feature to _Mark a thread as done_ was introduced somewhere between June 10, 2023[^1] and February
5, 2024[^2].


Did you discover the changelog for such updates for the `REST API`? Although there is a readily
accessible list of updates for the new additions to the `GraphQLAPI`[^3], I was under the impression
that no such resource existed for the `REST API`.



---


I am considering adding a hotkey to mark notifications as `DONE`, which would equivalent to marking
a notification in your notification inbox on GitHub as `DONE`. However, the challenge lies in the
fact that the Terminal would continue to display the same list, as the data does not reflect whether
a notification is `DONE` or not.

For instance, the notification I received from your comment carries the following information. Even
after marking it as `DONE`, the returned data remains unchanged. Therefore, pressing the hotkey
wouldn't convey any noticeable changes to the Terminal user. They would only become aware of the
change upon logging into their GitHub account and checking their inbox.

```json
{
"id": "6463980195",
"unread": false,
"reason": "state_change",
"updated_at": "2024-03-02T23:54:38Z",
"last_read_at": null,
"subject": {
	"title": "Show \"open\" notifications",
	"url": "https://api.github.com/repos/meiji163/gh-notify/issues/47",
	"latest_comment_url": "https://api.github.com/repos/meiji163/gh-notify/issues/comments/1974945563",
	"type": "Issue"
},
...

```

---

I would prefer to wait until Github introduces a new field for conveying the information, with a
`done: true/false` status.


[^1]: https://web.archive.org/web/20230610191811/https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28
[^2]: https://web.archive.org/web/20240205034519/https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28
[^3]: [GraphQL API Changelog - GitHub Docs](https://docs.github.com/en/graphql/overview/changelog)

**Comment by rmacklin** [comment]
Thanks for the detailed reply. Yeah, I see your point about not wanting to implement this if we can't distinguish the "done" items. It's quite frustrating that there's no property in the notification's JSON indicating that it was marked `done` (or [`saved`](https://github.com/notifications?query=is%3Asaved) for that matter) even after adding the "mark as done" API. Not sure why the API doesn't let us pass `query=is:done` like the web app does.

**Comment by sitano** [comment]
edit: oh, now I see read feed.

~~Why do we need to distinguish `is:done` entries if they are DELETED with the done action? so they are no appear in the notifications feed. #91 works great for me. See `--method DELETE` https://github.com/meiji163/gh-notify/pull/91/files#diff-d286f9120037bbf01847f2c1283501f4a44c6943ee65ed1783edf64088f2b584R553.~~

**Comment by sitano** [comment]
~~it seems the status `is:read` can be distinguished by checking 2 fields in conjunction `unread == false && last_read_at != NULL` whereas `is:done` have `last_read_at == NULL`, like in:~~
```
  {
    "id": "11615952375",
    "unread": false,
    "reason": "review_requested",
    "updated_at": "2024-07-23T10:46:01Z",
    "last_read_at": "2024-07-23T13:38:55Z",
    ...
  }
```
~~this is done~~
```
  {
    "id": "11615952375",
    "unread": false,
    "reason": "review_requested",
    "updated_at": "2024-07-23T10:46:01Z",
    "last_read_at": NULL,
    ...
  }
```

**Comment by sitano** [comment]
btw, for `git notify -a` I think it needs a page limit (not to load everything at once) cuz every reload is painful.

**Comment by rmacklin** [comment]
> it seems the status `is:read` can be distinguished by checking 2 fields in conjunction `unread == false && last_read_at != NULL` whereas `is:done` have `last_read_at == NULL`

I'm not seeing the same. I have many notifications that have been marked as "Done" in the web UI which still appear in the API as `"unread": false` with a non-null `last_read_at`.

The only time a notification would appear `"unread": false` with a null `last_read_at` is if you mark it as done without ever having opened that object. Even if you get a new notification for the same issue/PR/etc that you had previously opened, but you do not open it again, it will still have a non-null `last_read_at` (both before and after marking it as done without opening it).

So unfortunately, it doesn't seem like check would work for correctly distinguishing "done" notifications.

**Comment by sitano** [comment]
@rmacklin you are right. I confused that a bit.

**Comment by sitano** [comment]
I completely agree with the arguments. I wanted to share that I am now using a version from my PR with CTRL+x for done-ning the issues instead of using the main GH UI and its still super convenient even without the ability to list read but undone items.
