### ISSUE TITLE
Feature Request: Keyboard shortcut to mark current notification as done

### ISSUE THREAD

**Issue by andres-lowrie** [meiji163/gh-notify#51]
Great plugin !!! 

I see that `ctrl-r` marks all of the notification as done, Given that I tend to use the preview view and look at the messages that way (like an inbox almost) I think it would be cool to add a keyboard shortcut to just mark the current notification as done instead of all of them

**Comment by LangLangBart** [comment]
> _Great plugin !!!_

:thumbsup:

---

- just a clarification, currently there is no way to mark a notification as `done` through the GitHub API
- Related thread: [Expose notification mark as done functionality through API #15669](https://github.com/orgs/community/discussions/15669)
- i assume you meant to mark a notification as `read`
  - started a pull request, will do more testing and might merge next week

**Comment by andres-lowrie** [comment]
sweet !!!
