### ISSUE TITLE
"line 99: syntax error near unexpected token"

### ISSUE THREAD

**Issue by LangLangBart** [meiji163/gh-notify#7]
### description
Getting an error when running `gh notify`

### to reproduce
- Install the latest version  `gh extension install meiji163/gh-notify`
- Run `gh notify`
- Error, see the terminal output and the image below for more clarity
```zsh
❯ gh notify
/Users/paria/.local/share/gh/extensions/gh-notify/gh-notify: line 99: syntax error near unexpected token `;;'
```

### bisect
The error came with commit 23af7021e7589c38d93514ede9a8c9a810ffd4dc.
<img src="https://ttm.sh/wkd.48.jpg" width="600">

**Comment by meiji163** [comment]
Thanks for the report! I can reproduce this with bash v3.2 but not bash v5.1
@masukomi any idea? 

I'll look into it when I have time

**Comment by meiji163** [comment]
Turns out bash 3 can't use `case` inside `$(...)`, but it works with backticks

**Comment by LangLangBart** [comment]
🙂
Thank you for solving my issue so quickly (tested on macOS with `zsh`).
