### ISSUE TITLE
Some types of notifications aren't supported

### ISSUE THREAD

**Issue by pcrock-thmdo** [meiji163/gh-notify#77]
So far I've noticed that github security alerts (at least) aren't supported. The web UI can look like this...

![image](https://github.com/meiji163/gh-notify/assets/122453313/59d5b463-d5ad-4452-be8e-cef9896fbe8a)

but it won't show up in, for example, `gh notify -asn 50`

i haven't looked into the github API too much, but are these kinds of notifications possible to support as well?

**Comment by LangLangBart** [comment]
> So far I've noticed that github security alerts (at least) aren't supported. The web UI can look
> like this...


This could be related to the `REST API` for notifications. I've spotted some discrepancies between
what is displayed in the WebUI and what can be extracted via the `REST API`. For instance,
information about whether a PR/Issue is open, closed, or merged isn't included in the response. As a
result, all notification numbers are displayed in green. Processing each data point individually
with the REST API is resource-intensive and time-consuming.


---


In your case, we're not displaying certain information, such as the notification reason[^1].

| Notification Reason | Description                                                    |
| ------------------- | -------------------------------------------------------------- |
| mention             | You were specifically @mentioned in the content.               |
| security_alert      | GitHub discovered a security vulnerability in your repository. |
| …                   | …                                                              |

If we were to display the `reason`, it might appear as follows:

<img
src="https://github.com/meiji163/gh-notify/assets/92653266/e2317572-2d99-4416-9613-d270f7b5edc7"
width="800">


---

You could consider running the command below to see what types of notifications and reasons are
returned. If the desired information is included in the data, we can display it.


```bash
# List unique types/reasons of the last 50 notifications
gh api --method GET notifications --field all=true --field per_page=50 \
    --jq '.[] | "\(.reason)\t\(.subject.type)"' | sort -u | column -t
# author      Issue
# comment     Discussion
# comment     Issue
# manual      Issue
# mention     Issue
# mention     PullRequest
# subscribed  Discussion
# subscribed  Issue
# subscribed  PullRequest
```

[^1]: [REST API endpoints for notifications - GitHub Docs](https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#about-notification-reasons)

**Comment by pcrock-thmdo** [comment]
Ah, looks like it's a different API endpoint, and would require iterating through github orgs or repos. Ex:

```bash
gh api --method GET /orgs/${org_id}/dependabot/alerts \
  --field all=true --field per_page=50 \
  --jq '.[] | "\(.security_advisory.ghsa_id)\t\(.security_advisory.severity)"' \
  | sort -u \
  | column -t
```

would return something like this:

```plaintext
GHSA-3787-6prv-h9w3  low
GHSA-4gmj-3p3h-gm8h  low
GHSA-5fg8-2547-mr8q  medium
GHSA-6v6w-h8m6-7mv2  medium
GHSA-6vqw-3v5j-54x4  high
GHSA-6xwf-xvf3-v459  medium
GHSA-78xj-cgh5-2h22  medium
GHSA-9v9h-cgj8-h64p  medium
GHSA-j2pw-vp55-fqqj  critical
GHSA-p25m-jpj4-qcrr  high
GHSA-wf5p-g6vw-rhxx  medium
GHSA-xxj9-f6rv-m3x4  medium
```

so, looks like it would be nontrivial.

https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28

**Comment by LangLangBart** [comment]
> Ah, looks like it's a different API endpoint, and would require iterating through github orgs or repos. Ex:

Thank you for investigating.

At present, I do not plan to support these types of alerts. However, I might reconsider if the
`GraphQL API`[^1] supports `notifications` and `dependabot/alerts`, or if GitHub provides a simpler
way to obtain the same information through their `REST API` as seen in the WebUI.

[^1]: [Notifications GraphQL API · Discussion #13056](https://github.com/orgs/community/discussions/13056)
